<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>OSProductUpdatesProvider</AssemblyName>
    <RootNamespace>OutSystems.OSProductUpdatesProvider</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OutSystems.ExternalLibraries.SDK" Version="1.4.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\os_product_updates.png" />
  </ItemGroup>

</Project>
